--
-- PostgreSQL database dump
--

\restrict fgfwE0l4uFhvEX1qJjF2T2CqF6h2sY7NLZCZbPcXv2x5DVDAtPyld4cwGNLqmds

-- Dumped from database version 18.0 (Debian 18.0-1.pgdg12+3)
-- Dumped by pg_dump version 18.0 (Debian 18.0-1.pgdg12+3)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_products; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.cart_products (
    id_cart_product bigint NOT NULL,
    price double precision NOT NULL,
    quatity integer NOT NULL,
    id_cart bigint NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.cart_products OWNER TO admin;

--
-- Name: cart_products_id_cart_product_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.cart_products ALTER COLUMN id_cart_product ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_products_id_cart_product_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.categories (
    id_category bigint NOT NULL,
    category_name character varying(255) NOT NULL,
    description character varying(255) NOT NULL
);


ALTER TABLE public.categories OWNER TO admin;

--
-- Name: categories_id_category_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.categories ALTER COLUMN id_category ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_category_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.notifications (
    id_notification bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    delivery_date timestamp(6) without time zone,
    email_sent boolean NOT NULL,
    message character varying(2000) NOT NULL,
    send_at timestamp(6) without time zone NOT NULL,
    subject character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_dpi character varying(255) NOT NULL,
    error_message character varying(255)
);


ALTER TABLE public.notifications OWNER TO admin;

--
-- Name: notifications_id_notification_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.notifications ALTER COLUMN id_notification ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_notification_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_products; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.order_products (
    id_order_product bigint NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    id_order bigint NOT NULL,
    product_id bigint
);


ALTER TABLE public.order_products OWNER TO admin;

--
-- Name: order_products_id_order_product_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.order_products ALTER COLUMN id_order_product ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_products_id_order_product_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.orders (
    id_order bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    delivery_date timestamp(6) without time zone NOT NULL,
    status boolean NOT NULL,
    total_amount double precision NOT NULL,
    id_cart bigint NOT NULL,
    user_dpi character varying(255)
);


ALTER TABLE public.orders OWNER TO admin;

--
-- Name: orders_id_order_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.orders ALTER COLUMN id_order ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_order_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.products (
    product_id bigint NOT NULL,
    condition boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(1000) NOT NULL,
    image character varying(900),
    price double precision NOT NULL,
    product_name character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    stock integer NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    id_category bigint NOT NULL,
    user_dpi character varying(255) NOT NULL,
    CONSTRAINT products_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.products OWNER TO admin;

--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.products ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ratings; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.ratings (
    id_rating bigint NOT NULL,
    comment character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    starts integer NOT NULL,
    product_id bigint NOT NULL,
    user_dpi character varying(255) NOT NULL
);


ALTER TABLE public.ratings OWNER TO admin;

--
-- Name: ratings_id_rating_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.ratings ALTER COLUMN id_rating ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ratings_id_rating_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.roles (
    id_role bigint NOT NULL,
    description character varying(255) NOT NULL,
    name_role character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO admin;

--
-- Name: roles_id_role_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.roles ALTER COLUMN id_role ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_role_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sanctions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.sanctions (
    id_sanction bigint NOT NULL,
    end_date timestamp(6) without time zone,
    reason character varying(255) NOT NULL,
    start_date timestamp(6) without time zone DEFAULT now() NOT NULL,
    status boolean DEFAULT true NOT NULL,
    moderator_dpi character varying(255) NOT NULL,
    user_dpi character varying(255) NOT NULL,
    violation_type character varying(255) NOT NULL
);


ALTER TABLE public.sanctions OWNER TO admin;

--
-- Name: sanctions_id_sanction_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.sanctions ALTER COLUMN id_sanction ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sanctions_id_sanction_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: shopping_carts; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.shopping_carts (
    id_cart bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    status boolean NOT NULL,
    update_at timestamp(6) without time zone NOT NULL,
    user_dpi character varying(255) NOT NULL
);


ALTER TABLE public.shopping_carts OWNER TO admin;

--
-- Name: shopping_carts_id_cart_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.shopping_carts ALTER COLUMN id_cart ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shopping_carts_id_cart_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_cards; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_cards (
    id_card bigint NOT NULL,
    card_holder character varying(255) NOT NULL,
    card_number character varying(16) NOT NULL,
    card_type character varying(255) NOT NULL,
    expiration_date character varying(255) NOT NULL,
    security_code character varying(255) NOT NULL,
    user_dpi character varying(255) NOT NULL
);


ALTER TABLE public.user_cards OWNER TO admin;

--
-- Name: user_cards_id_card_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.user_cards ALTER COLUMN id_card ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_cards_id_card_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    user_dpi character varying(255) NOT NULL,
    address character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    status boolean NOT NULL,
    id_role bigint
);


ALTER TABLE public.users OWNER TO admin;

--
-- Name: cart_products cart_products_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart_products
    ADD CONSTRAINT cart_products_pkey PRIMARY KEY (id_cart_product);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id_category);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id_notification);


--
-- Name: order_products order_products_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_products
    ADD CONSTRAINT order_products_pkey PRIMARY KEY (id_order_product);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id_order);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (product_id);


--
-- Name: ratings ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT ratings_pkey PRIMARY KEY (id_rating);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id_role);


--
-- Name: sanctions sanctions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sanctions
    ADD CONSTRAINT sanctions_pkey PRIMARY KEY (id_sanction);


--
-- Name: shopping_carts shopping_carts_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.shopping_carts
    ADD CONSTRAINT shopping_carts_pkey PRIMARY KEY (id_cart);


--
-- Name: roles uk2op45rew8nnd6adyi86qeqk50; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT uk2op45rew8nnd6adyi86qeqk50 UNIQUE (description);


--
-- Name: user_cards user_cards_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_cards
    ADD CONSTRAINT user_cards_pkey PRIMARY KEY (id_card);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_dpi);


--
-- Name: ratings fk228us4dg38ewge41gos8y761r; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT fk228us4dg38ewge41gos8y761r FOREIGN KEY (product_id) REFERENCES public.products(product_id);


--
-- Name: order_products fk2dsdad0hrbro0jpbv24abdmae; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_products
    ADD CONSTRAINT fk2dsdad0hrbro0jpbv24abdmae FOREIGN KEY (id_order) REFERENCES public.orders(id_order);


--
-- Name: ratings fk4qnubeecj1dee5b4c0rsadm8k; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ratings
    ADD CONSTRAINT fk4qnubeecj1dee5b4c0rsadm8k FOREIGN KEY (user_dpi) REFERENCES public.users(user_dpi);


--
-- Name: shopping_carts fk9s5xjgkyjq8ec58du0owsr0lr; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.shopping_carts
    ADD CONSTRAINT fk9s5xjgkyjq8ec58du0owsr0lr FOREIGN KEY (user_dpi) REFERENCES public.users(user_dpi);


--
-- Name: sanctions fk_moderator_sanction; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sanctions
    ADD CONSTRAINT fk_moderator_sanction FOREIGN KEY (moderator_dpi) REFERENCES public.users(user_dpi);


--
-- Name: sanctions fk_user_sanction; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.sanctions
    ADD CONSTRAINT fk_user_sanction FOREIGN KEY (user_dpi) REFERENCES public.users(user_dpi);


--
-- Name: orders fkau4e2tm6m6b05t4k64r0qxba3; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkau4e2tm6m6b05t4k64r0qxba3 FOREIGN KEY (id_cart) REFERENCES public.shopping_carts(id_cart);


--
-- Name: cart_products fkdayy17at10up1qqwlri9cocb3; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart_products
    ADD CONSTRAINT fkdayy17at10up1qqwlri9cocb3 FOREIGN KEY (product_id) REFERENCES public.products(product_id);


--
-- Name: order_products fkdxjduvg7991r4qja26fsckxv8; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.order_products
    ADD CONSTRAINT fkdxjduvg7991r4qja26fsckxv8 FOREIGN KEY (product_id) REFERENCES public.products(product_id);


--
-- Name: cart_products fkf6kjmchiyse81k95b2dctj1dw; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.cart_products
    ADD CONSTRAINT fkf6kjmchiyse81k95b2dctj1dw FOREIGN KEY (id_cart) REFERENCES public.shopping_carts(id_cart);


--
-- Name: orders fkhkurdckx81oh6owsu2wf8i8j4; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkhkurdckx81oh6owsu2wf8i8j4 FOREIGN KEY (user_dpi) REFERENCES public.users(user_dpi);


--
-- Name: user_cards fkiaijomlqvk6ksbsmqpad27e9q; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_cards
    ADD CONSTRAINT fkiaijomlqvk6ksbsmqpad27e9q FOREIGN KEY (user_dpi) REFERENCES public.users(user_dpi);


--
-- Name: products fkip7b0y8ja7fsm5wl7mhmseh5n; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkip7b0y8ja7fsm5wl7mhmseh5n FOREIGN KEY (id_category) REFERENCES public.categories(id_category);


--
-- Name: notifications fkk7aehofgbisghgcnbo8tvusrs; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fkk7aehofgbisghgcnbo8tvusrs FOREIGN KEY (user_dpi) REFERENCES public.users(user_dpi);


--
-- Name: products fkmqxmb6gvugjw6e23s9iofcyvn; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fkmqxmb6gvugjw6e23s9iofcyvn FOREIGN KEY (user_dpi) REFERENCES public.users(user_dpi);


--
-- Name: users fkt92dgi4412ywy3u8tm9jwdya5; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkt92dgi4412ywy3u8tm9jwdya5 FOREIGN KEY (id_role) REFERENCES public.roles(id_role);


--
-- PostgreSQL database dump complete
--

\unrestrict fgfwE0l4uFhvEX1qJjF2T2CqF6h2sY7NLZCZbPcXv2x5DVDAtPyld4cwGNLqmds

